### ISSUE TITLE
Add support for custom named climate type's.

### ISSUE THREAD

**Issue by brianGit78** [Einstein42/udi-ecobee-poly#1]
I get the following error when I run the Ecobee Node Server for about 24 hours:

2018-10-16 07:01:53,638 DEBUG    Update detected in thermostat Main Floor(511866920242) doing full update.
2018-10-16 07:01:53,640 DEBUG    Tokens valid until: 2018-10-16T07:37:52
2018-10-16 07:01:53,641 INFO     Getting Full Thermostat Data for 511866920242
2018-10-16 07:01:54,049 ERROR    Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/.local/lib/python3.5/site-packages/polyinterface/polyinterface.py", line 738, in _parseInput
    self.longPoll()
  File "./ecobee-poly.py", line 176, in longPoll
    self.updateThermostats()
  File "./ecobee-poly.py", line 189, in updateThermostats
    self.nodes[thermostatId].update(thermostat, fullData)
  File "/home/pi/.polyglot/nodeservers/Ecobee/node_types.py", line 207, in update
    'GV3': climateMap[self.program['currentClimateRef']],
KeyError: 'wakeup'

**Comment by jimboca** [comment]
I see the issue here, the nodeserver only understands these:

```
climateMap = {
  'away': 0,
  'home': 1,
  'sleep': 2,
  'smart1': 3,
  'smart2': 4,
  'smart3': 5,
  'smart4': 6,
  'smart5': 7,
  'smart6': 8,
  'smart7': 9,
  'unknown': 10
}
```
and you have named one 'wakeup'.   Will need to figure out how to support custom named climate modes.   This will require the profile be custom generated for each person.

**Comment by jimboca** [comment]
This will be more effort so pushed out to after the next release.  If you change the name from wakeup back to smart1 then it will no longer crash. :)

**Comment by jimboca** [comment]
The code is fixed to not crash, it will not proper climate type in the ISY Admin Console, but everything else should work.
Will work on supporting custom names soon.

**Comment by jimboca** [comment]
This should all be fixed now, please let me know if it's working for you and I will close.

**Comment by jimboca** [comment]
All working in 2.0.17
