### ISSUE TITLE
Trap: ConnectionResetError: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by jimboca** [Einstein42/udi-ecobee-poly#39]
This caused the thread to die?  Need to trap exception. Main process was still running but log showed nothing.

```
2019-02-19 05:25:43,782 [Controller] [DEBUG] heartbeat hb=0
2019-02-19 05:25:43,784 [Controller] [DEBUG] controller:updateThermostats:
2019-02-19 05:25:43,786 [Controller] [DEBUG] Tokens valid until: 2019-02-19T06:22:45
2019-02-19 05:25:51,980 [Controller] [ERROR] Exception in thread Controller:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/.local/lib/python3.5/site-packages/polyinterface/polyinterface.py", line 771, in _parseInput
    self.longPoll()
  File "./ecobee-poly.py", line 240, in longPoll
    self.updateThermostats()
  File "./ecobee-poly.py", line 253, in updateThermostats
    thermostats = self.getThermostats()
  File "./ecobee-poly.py", line 470, in getThermostats
    res = auth_conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1198, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 576, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.5/ssl.py", line 937, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.5/ssl.py", line 799, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.5/ssl.py", line 583, in read
    v = self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer
```

**Comment by jimboca** [comment]
Should be fixed in 2.0.36
