### ISSUE TITLE
Crash due to bad json returned from Ecobee

### ISSUE THREAD

**Issue by jimboca** [Einstein42/udi-ecobee-poly#45]
```
2019-04-09 14:14:49,829 [Controller] [ERROR] Ecobee Controller:reponse:get: Failed to convert to json : Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/pi/development/udi-ecobee-poly/pgSession.py", line 66, in response
    json_data = json.loads(response.text)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2019-04-09 14:14:49,866 [Controller] [DEBUG] controller:set_ecobee_st: True=1
2019-04-09 14:14:49,907 [Controller] [ERROR] Exception in thread Controller:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/.local/lib/python3.5/site-packages/polyinterface/polyinterface.py", line 771, in _parseInput
    self.longPoll()
  File "./ecobee-poly.py", line 202, in longPoll
    self.updateThermostats()
  File "./ecobee-poly.py", line 215, in updateThermostats
    thermostats = self.getThermostats()
  File "./ecobee-poly.py", line 446, in getThermostats
    if 'revisionList' in res_data:
TypeError: argument of type 'bool' is not iterable
```

**Comment by jimboca** [comment]
Fixed in 2.1.4
