### ISSUE TITLE
More API issues

### ISSUE THREAD

**Issue by jimboca** [Einstein42/udi-ecobee-poly#5]
https://forum.universal-devices.com/index.php?/topic/24876-Ecobee-Nodeserver-problem-v2.0.5#entry251957

It seem something has changed recently has the changing the mode from Home to Away is not longer working for me. Also changing the transition mode has no effect anymore. It seem I have also similar problem as @beninsteon
 Here a trace stack, when I tried to change mode :

2018-11-28 22:45:17,332 ERROR _parseInput: failed 311013547759.runCmd(CLISMD) int() argument must be a string, a bytes-like object or a number, not 'NoneType'
Traceback (most recent call last):
File "/root/.local/lib/python3.5/site-packages/polyinterface/polyinterface.py", line 726, in _parseInput
self.nodes[input[key]['address']].runCmd(input[key])
File "/root/.local/lib/python3.5/site-packages/polyinterface/polyinterface.py", line 631, in runCmd
fun(self, command)
File "/root/.polyglot/nodeservers/Ecobee/node_types.py", line 263, in cmdSetScheduleMode
heatHoldTemp = int(self.getDriver('CLISPH'))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by jimboca** [comment]
This was because the Thermostat node defined it's own getDriver method, which has been broken for a while.
