### ISSUE TITLE
Aux Heat Only causes crash

### ISSUE THREAD

**Issue by macjeff** [Einstein42/udi-ecobee-poly#50]
Ecobee 4-  Name comes in automatically as well as all the sensor names but all of them show no values.  Figured out from log its AUX Heat Only.  Set to regular heat and we are ok
```
2020-01-26 17:34:09,397 [Controller] [DEBUG] ECO_CTR:Ecobee Controller:session_get: res={'code': 200, 'data': {'page': {'page': 1, 'totalPages': 1, 'pageSize': 1, 'total': 1}, 'thermostatList': [{'identifier': '311059459667', 'name': 'Upstairs', 'thermostatRev': '200126220713', 'isRegistered': True, 'modelNumber': 'athenaSmart', 'brand': 'ecobee', 'features': 'Home,HomeKit', 'lastModified': '2020-01-26 22:07:13', 'thermostatTime': '2020-01-26 17:34:09', 'utcTime': '2020-01-26 22:34:09', 'alerts': [], 'settings': {'hvacMode': 'auxHeatOnly', 'lastServiceDate': '2019-10-09', 'serviceRemindMe': True, 'monthsBetweenService': 6, 'remindMeDate': '2020-04-09', 'vent': 'off', 'ventilatorMinOnTime': 20, 'serviceRemindTechnician': False, 'eiLocation': '', 'coldTempAlert': 580, 'coldTempAlertEnabled': True, 'hotTempAlert': 850, 'hotTempAlertEnabled': True, 'coolStages': 1, 'heatStages': 1, 'maxSetBack': 100, 'maxSetForward': 80, 'quickSaveSetBack': 40, 'quickSaveSetForward': 40, 'hasHeatPump': True, 'hasForcedAir': True, 'hasBoiler': False, 'hasHumidifier': False, 'hasErv': False, 'hasHrv': False, 'condensationAvoid': False, 'useCelsius': False, 'useTimeFormat12': True, 'locale': 'en', 'humidity': '36', 'humidifierMode': 'off', 'backlightOnIntensity': 10, 'backlightSleepIntensity': 4, 'backlightOffTime': 60, 'soundTickVolume': 0, 'soundAlertVolume': 0, 'compressorProtectionMinTime': 300, 'compressorProtectionMinTemp': -10000, 'stage1HeatingDifferentialTemp': 5, 'stage1CoolingDifferentialTemp': 5, 'stage1HeatingDissipationTime': 31, 'stage1CoolingDissipationTime': 31, 'heatPumpReversalOnCool': True, 'fanControlRequired': False, 'fanMinOnTime': 0, 'heatCoolMinDelta': 50, 'tempCorrection': 0, 'holdAction': 'indefinite', 'heatPumpGroundWater': False, 'hasElectric': False, 'hasDehumidifier': False, 'dehumidifierMode': 'off', 'dehumidifierLevel': 60, 'dehumidifyWithAC': False, 'dehumidifyOvercoolOffset': 0, 'autoHeatCoolFeatureEnabled': True, 'wifiOfflineAlert': False, 'heatMinTemp': 450, 'heatMaxTemp': 1200, 'coolMinTemp': -100, 'coolMaxTemp': 1200, 'heatRangeHigh': 790, 'heatRangeLow': 450, 'coolRangeHigh': 920, 'coolRangeLow': 650, 'userAccessCode': '', 'userAccessSetting': 0, 'auxRuntimeAlert': 21600, 'auxOutdoorTempAlert': 500, 'auxMaxOutdoorTemp': 350, 'auxRuntimeAlertNotify': True, 'auxOutdoorTempAlertNotify': False, 'auxRuntimeAlertNotifyTechnician': False, 'auxOutdoorTempAlertNotifyTechnician': False, 'disablePreHeating': False, 'disablePreCooling': False, 'installerCodeRequired': False, 'drAccept': 'always', 'isRentalProperty': False, 'useZoneController': False, 'randomStartDelayCool': 0, 'randomStartDelayHeat': 0, 'humidityHighAlert': 95, 'humidityLowAlert': 5, 'disableHeatPumpAlerts': False, 'disableAlertsOnIdt': False, 'humidityAlertNotify': True, 'humidityAlertNotifyTechnician': False, 'tempAlertNotify': True, 'tempAlertNotifyTechnician': False, 'monthlyElectricityBillLimit': 0, 'enableElectricityBillAlert': False, 'enableProjectedElectricityBillAlert': False, 'electricityBillingDayOfMonth': 1, 'electricityBillCycleMonths': 1, 'electricityBillStartMonth': 1, 'ventilatorMinOnTimeHome': 20, 'ventilatorMinOnTimeAway': 0, 'backlightOffDuringSleep': False, 'autoAway': False, 'smartCirculation': False, 'followMeComfort': False, 'ventilatorType': 'none', 'isVentilatorTimerOn': False, 'ventilatorOffDateTime': '', 'hasUVFilter': True, 'coolingLockout': False, 'ventilatorFreeCooling': True, 'dehumidifyWhenHeating': False, 'ventilatorDehumidify': True, 'groupRef': '', 'groupName': '', 'groupSetting': 0}, 'runtime': {'runtimeRev': '200126223240', 'connected': True, 'firstConnected': '2017-03-15 17:32:36', 'connectDateTime': '2020-01-26 21:54:47', 'disconnectDateTime': '2020-01-26 09:27:28', 'lastModified': '2020-01-26 22:32:40', 'lastStatusModified': '2020-01-26 22:32:40', 'runtimeDate': '2020-01-26', 'runtimeInterval': 267, 'actualTemperature': 707, 'actualHumidity': 32, 'rawTemperature': 707, 'showIconMode': 0, 'desiredHeat': 680, 'desiredCool': 720, 'desiredHumidity': 36, 'desiredDehumidity': 60, 'desiredFanMode': 'auto', 'desiredHeatRange': [450, 790], 'desiredCoolRange': [650, 920]}, 'extendedRuntime': {'lastReadingTimestamp': '2020-01-26 22:15:00', 'runtimeDate': '2020-01-26', 'runtimeInterval': 267, 'actualTemperature': [714, 711, 709], 'actualHumidity': [33, 33, 33], 'desiredHeat': [680, 680, 680], 'desiredCool': [720, 720, 720], 'desiredHumidity': [0, 0, 0], 'desiredDehumidity': [0, 0, 0], 'dmOffset': [0, 0, 0], 'hvacMode': ['heatOff', 'heatOff', 'heatOff'], 'heatPump1': [0, 0, 0], 'heatPump2': [0, 0, 0], 'auxHeat1': [0, 0, 0], 'auxHeat2': [0, 0, 0], 'auxHeat3': [0, 0, 0], 'cool1': [0, 0, 0], 'cool2': [0, 0, 0], 'fan': [0, 0, 0], 'humidifier': [0, 0, 0], 'dehumidifier': [0, 0, 0], 'economizer': [0, 0, 0], 'ventilator': [0, 0, 0], 'currentElectricityBill': 0, 'projectedElectricityBill': 0}, 'location': {'timeZoneOffsetMinutes': -300, 'timeZone': 'America/New_York', 'isDaylightSaving': True, 'streetAddress': '16806 Heather Knolls Place', 'city': 'Hamilton', 'provinceState': 'VA', 'country': 'US', 'postalCode': '20158', 'phoneNumber': '', 'mapCoordinates': '39.152397,-77.666695'}, 'utility': {}, 'weather': {'timestamp': '2020-01-26 22:33:02', 'weatherStation': 'FI:KJYO', 'forecasts': [{'weatherSymbol': 3, 'dateTime': '2020-01-26 17:33:02', 'condition': 'Overcast', 'temperature': 410, 'pressure': 1012, 'relativeHumidity': 69, 'dewpoint': 317, 'visibility': 10000, 'windSpeed': 6, 'windGust': -5002, 'windDirection': 'W', 'windBearing': 281, 'pop': 0, 'tempHigh': 454, 'tempLow': 332, 'sky': 5}, {'weatherSymbol': 2, 'dateTime': '2020-01-27 00:00:00', 'condition': 'Partly cloudy throughout the day.', 'temperature': 401, 'pressure': 1010, 'relativeHumidity': 71, 'dewpoint': 298, 'visibility': 16000, 'windSpeed': 7, 'windGust': -5002, 'windDirection': 'W', 'windBearing': 278, 'pop': 15, 'tempHigh': 496, 'tempLow': 307, 'sky': 2}, {'weatherSymbol': 0, 'dateTime': '2020-01-28 00:00:00', 'condition': 'Clear throughout the day.', 'temperature': 390, 'pressure': 1014, 'relativeHumidity': 68, 'dewpoint': 273, 'visibility': 16000, 'windSpeed': 9, 'windGust': -5002, 'windDirection': 'NW', 'windBearing': 316, 'pop': 9, 'tempHigh': 464, 'tempLow': 317, 'sky': 2}, {'weatherSymbol': 0, 'dateTime': '2020-01-29 00:00:00', 'condition': 'Clear throughout the day.', 'temperature': 364, 'pressure': 1019, 'relativeHumidity': 66, 'dewpoint': 239, 'visibility': 16000, 'windSpeed': 7, 'windGust': -5002, 'windDirection': 'NNW', 'windBearing': 327, 'pop': 3, 'tempHigh': 444, 'tempLow': 284, 'sky': 2}, {'weatherSymbol': 2, 'dateTime': '2020-01-30 00:00:00', 'condition': 'Partly cloudy throughout the day.', 'temperature': 333, 'pressure': 1024, 'relativeHumidity': 55, 'dewpoint': 157, 'visibility': 16000, 'windSpeed': 3, 'windGust': -5002, 'windDirection': 'NNE', 'windBearing': 31, 'pop': 2, 'tempHigh': 435, 'tempLow': 231, 'sky': 3}, {'weatherSymbol': 1, 'dateTime': '2020-01-26 18:00:00', 'condition': 'Mostly Cloudy', 'temperature': 398, 'pressure': 1012, 'relativeHumidity': 71, 'dewpoint': 311, 'visibility': 10000, 'windSpeed': 6, 'windGust': -5002, 'windDirection': 'W', 'windBearing': 280, 'pop': 4, 'tempHigh': -5002, 'tempLow': -5002, 'sky': 4}, {'weatherSymbol': 0, 'dateTime': '2020-01-27 00:00:00', 'condition': 'Clear', 'temperature': 345, 'pressure': 1012, 'relativeHumidity': 75, 'dewpoint': 274, 'visibility': 16000, 'windSpeed': 5, 'windGust': -5002, 'windDirection': 'SW', 'windBearing': 221, 'pop': 2, 'tempHigh': -5002, 'tempLow': -5002, 'sky': 1}, {'weatherSymbol': 1, 'dateTime': '2020-01-27 06:00:00', 'condition': 'Mostly Cloudy', 'temperature': 324, 'pressure': 1011, 'relativeHumidity': 86, 'dewpoint': 287, 'visibility': 16000, 'windSpeed': 5, 'windGust': -5002, 'windDirection': 'SW', 'windBearing': 222, 'pop': 2, 'tempHigh': -5002, 'tempLow': -5002, 'sky': 3}, {'weatherSymbol': 2, 'dateTime': '2020-01-27 12:00:00', 'condition': 'Partly Cloudy', 'temperature': 460, 'pressure': 1009, 'relativeHumidity': 59, 'dewpoint': 325, 'visibility': 16000, 'windSpeed': 9, 'windGust': -5002, 'windDirection': 'N', 'windBearing': 1, 'pop': 0, 'tempHigh': -5002, 'tempLow': -5002, 'sky': 2}]}, 'events': [], 'program': {'schedule': [['sleep', 'sleep', 'sleep', 'sleep', 'sleep', 'sleep', 'sleep', 'sleep', 'sleep', 'sleep', 'sleep', 'sleep', 'sleep', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'sleep'], ['sleep', 'sleep', 'sleep', 'sleep', 'sleep', 'sleep', 'sleep', 'sleep', 'sleep', 'sleep', 'sleep', 'sleep', 'sleep', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'sleep'], ['sleep', 'sleep', 'sleep', 'sleep', 'sleep', 'sleep', 'sleep', 'sleep', 'sleep', 'sleep', 'sleep', 'sleep', 'sleep', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'sleep'], ['sleep', 'sleep', 'sleep', 'sleep', 'sleep', 'sleep', 'sleep', 'sleep', 'sleep', 'sleep', 'sleep', 'sleep', 'sleep', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'sleep'], ['sleep', 'sleep', 'sleep', 'sleep', 'sleep', 'sleep', 'sleep', 'sleep', 'sleep', 'sleep', 'sleep', 'sleep', 'sleep', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'sleep'], ['sleep', 'sleep', 'sleep', 'sleep', 'sleep', 'sleep', 'sleep', 'sleep', 'sleep', 'sleep', 'sleep', 'sleep', 'sleep', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'sleep'], ['sleep', 'sleep', 'sleep', 'sleep', 'sleep', 'sleep', 'sleep', 'sleep', 'sleep', 'sleep', 'sleep', 'sleep', 'sleep', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'home', 'sleep']], 'climates': [{'name': 'Sleep', 'climateRef': 'sleep', 'isOccupied': True, 'isOptimized': False, 'coolFan': 'auto', 'heatFan': 'auto', 'vent': 'off', 'ventilatorMinOnTime': 20, 'owner': 'system', 'type': 'program', 'colour': 2179683, 'coolTemp': 740, 'heatTemp': 660, 'sensors': [{'id': 'ei:0:1', 'name': 'Upstairs'}, {'id': 'rs:102:1', 'name': 'Ashtons Room'}, {'id': 'rs:103:1', 'name': 'Tuckers Room'}, {'id': 'rs2:100:1', 'name': 'Sitting Room 2'}]}, {'name': 'Away', 'climateRef': 'away', 'isOccupied': False, 'isOptimized': True, 'coolFan': 'auto', 'heatFan': 'auto', 'vent': 'off', 'ventilatorMinOnTime': 20, 'owner': 'system', 'type': 'program', 'colour': 9021815, 'coolTemp': 760, 'heatTemp': 640, 'sensors': [{'id': 'ei:0:1', 'name': 'Upstairs'}, {'id': 'rs:102:1', 'name': 'Ashtons Room'}, {'id': 'rs:103:1', 'name': 'Tuckers Room'}, {'id': 'rs2:100:1', 'name': 'Sitting Room 2'}]}, {'name': 'Home', 'climateRef': 'home', 'isOccupied': True, 'isOptimized': False, 'coolFan': 'auto', 'heatFan': 'auto', 'vent': 'off', 'ventilatorMinOnTime': 20, 'owner': 'system', 'type': 'program', 'colour': 13560055, 'coolTemp': 720, 'heatTemp': 680, 'sensors': [{'id': 'ei:0:1', 'name': 'Upstairs'}, {'id': 'rs:102:1', 'name': 'Ashtons Room'}, {'id': 'rs:103:1', 'name': 'Tuckers Room'}, {'id': 'rs2:100:1', 'name': 'Sitting Room 2'}]}], 'currentClimateRef': 'home'}, 'equipmentStatus': '', 'version': {'thermostatFirmwareVersion': '4.5.13.45'}, 'remoteSensors': [{'id': 'rs:100', 'name': 'Sitting Room', 'type': 'ecobee3_remote_sensor', 'code': 'QCBF', 'inUse': False, 'capability': [{'id': '1', 'type': 'temperature', 'value': '721'}, {'id': '2', 'type': 'occupancy', 'value': 'true'}]}, {'id': 'rs:101', 'name': 'Guest Room', 'type': 'ecobee3_remote_sensor', 'code': 'V7NR', 'inUse': False, 'capability': [{'id': '1', 'type': 'temperature', 'value': '687'}, {'id': '2', 'type': 'occupancy', 'value': 'false'}]}, {'id': 'rs:102', 'name': 'Ashtons Room', 'type': 'ecobee3_remote_sensor', 'code': 'V32S', 'inUse': True, 'capability': [{'id': '1', 'type': 'temperature', 'value': '690'}, {'id': '2', 'type': 'occupancy', 'value': 'true'}]}, {'id': 'rs:103', 'name': 'Tuckers Room', 'type': 'ecobee3_remote_sensor', 'code': 'RJC6', 'inUse': True, 'capability': [{'id': '1', 'type': 'temperature', 'value': '701'}, {'id': '2', 'type': 'occupancy', 'value': 'true'}]}, {'id': 'ei:0', 'name': 'Upstairs', 'type': 'thermostat', 'inUse': True, 'capability': [{'id': '1', 'type': 'temperature', 'value': '714'}, {'id': '2', 'type': 'humidity', 'value': '32'}, {'id': '3', 'type': 'occupancy', 'value': 'true'}]}, {'id': 'rs2:100', 'name': 'Sitting Room 2', 'type': 'ecobee3_remote_sensor', 'code': 'KYRM', 'inUse': True, 'capability': [{'id': '1', 'type': 'temperature', 'value': '723'}, {'id': '2', 'type': 'occupancy', 'value': 'true'}]}]}], 'status': {'code': 0, 'message': ''}}}
2020-01-26 17:34:09,398 [Controller] [DEBUG] ECO_CTR:Ecobee Controller:getThermostatSelection: done
2020-01-26 17:34:09,401 [Controller] [DEBUG] EcobeeF_311059459667:t311059459667:Ecobee - Upstairs:update: 
2020-01-26 17:34:09,403 [Controller] [DEBUG] EcobeeF_311059459667:t311059459667:Ecobee - Upstairs:_update::  runtime={
  "actualHumidity": 32,
  "actualTemperature": 707,
  "connectDateTime": "2020-01-26 21:54:47",
  "connected": true,
  "desiredCool": 720,
  "desiredCoolRange": [
    650,
    920
  ],
  "desiredDehumidity": 60,
  "desiredFanMode": "auto",
  "desiredHeat": 680,
  "desiredHeatRange": [
    450,
    790
  ],
  "desiredHumidity": 36,
  "disconnectDateTime": "2020-01-26 09:27:28",
  "firstConnected": "2017-03-15 17:32:36",
  "lastModified": "2020-01-26 22:32:40",
  "lastStatusModified": "2020-01-26 22:32:40",
  "rawTemperature": 707,
  "runtimeDate": "2020-01-26",
  "runtimeInterval": 267,
  "runtimeRev": "200126223240",
  "showIconMode": 0
}
2020-01-26 17:34:09,404 [Controller] [DEBUG] EcobeeF_311059459667:t311059459667:Ecobee - Upstairs:_update: events=[]
2020-01-26 17:34:09,404 [Controller] [DEBUG] EcobeeF_311059459667:t311059459667:Ecobee - Upstairs:_update: climateType=home
2020-01-26 17:34:09,405 [Controller] [DEBUG] EcobeeF_311059459667:t311059459667:Ecobee - Upstairs:_update: clifrs=0 (equipmentStatus=[''] or clihcs=0, fanControlRequired=False
2020-01-26 17:34:09,406 [Controller] [DEBUG] EcobeeF_311059459667:t311059459667:Ecobee - Upstairs:_update: backlightOnIntensity=10 backlightSleepIntensisty=4
2020-01-26 17:34:09,415 [Controller] [ERROR] Exception in thread Controller:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/var/polyglot/.local/lib/python3.7/site-packages/polyinterface/polyinterface.py", line 858, in _parseInput
    self.longPoll()
  File "./ecobee-poly.py", line 204, in longPoll
    self.updateThermostats()
  File "./ecobee-poly.py", line 228, in updateThermostats
    self.nodes[address].update(thermostat, fullData)
  File "/var/polyglot/nodeservers/Ecobee/node_types.py", line 284, in update
    self._update()
  File "/var/polyglot/nodeservers/Ecobee/node_types.py", line 364, in _update
    'CLIMD': modeMap[self.settings['hvacMode']],
KeyError: 'auxHeatOnly'
```

**Comment by jimboca** [comment]
It should be fixed now, you can manually upgrade:https://github.com/Einstein42/udi-ecobee-poly/blob/master/README.md#manual-upgrade Or it should be in the store in 20 minutes or so...

**Comment by jimboca** [comment]
Confirmed to be fixed.
