### ISSUE TITLE
Crash getting date/time

### ISSUE THREAD

**Issue by jimboca** [Einstein42/udi-ecobee-poly#65]
```
2020-12-11 13:27:40,544 [Controller] [ERROR] Exception in thread Controller:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/pgc_interface/pgc_interface.py", line 797, in _parseInput
    self.longPoll()
  File "./ecobee-poly.py", line 427, in longPoll
    self.updateThermostats()
  File "./ecobee-poly.py", line 450, in updateThermostats
    fullData = self.getThermostatFull(thermostatId)
  File "./ecobee-poly.py", line 717, in getThermostatFull
    return self.getThermostatSelection(id,True,True,True,True,True,True,True,True,True,True,True,True)
  File "./ecobee-poly.py", line 733, in getThermostatSelection
    if not self._checkTokens():
  File "./ecobee-poly.py", line 115, in _checkTokens
    return self._getRefresh()
  File "./ecobee-poly.py", line 272, in _getRefresh
    if not self._startRefresh(test=test):
  File "./ecobee-poly.py", line 232, in _startRefresh
    l_dt = datetime.fromtimestamp(self._last_dtns).strftime(self._lock_fmt)
TypeError: an integer is required (got type str)
```

**Comment by jimboca** [comment]
Not fixed.  Need to properly format _last_dtns
